# Generated by Django 4.2.7 on 2023-12-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('publish_date', models.DateTimeField()),
                ('published', models.BooleanField(default=False)),
                ('cover_art', models.ImageField(upload_to='images/messages/')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='main_event',
            field=models.BooleanField(default=False),
        ),
    ]
